training_data = [
    ("Jaka jest pogoda w Szczecinie?", "pogoda"),
    ("Czy w Warszawie będzie padać deszcz?", "pogoda"),
    ("Temperatura w Poznaniu dzisiaj?", "pogoda"),
    ("Co to za pogoda w Warszawie?", "pogoda"),
    ("Kiedy wreszcie przestanie padać?", "pogoda"),
    ("Proszę, powiedz mi, która godzina?", "godzina"),
    ("Która godzina w Polsce?", "godzina"),
    ("Sprawdź, która godzina w USA", "godzina"),
    ("Jaką mamy godzinę w Ameryce?", "godzina"),
    ("Chciałbym wiedzieć, która jest teraz godzina we Francji", "godzina"),
    ("Jak mogę zmienić moje hasło?", "haslo"),
    ("Jak ustawić nowe hasło do mojego konta?", "haslo"),
    ("Potrzebuję pomocy w zmianie hasła", "haslo"),
    ("Chcę zmienić moje hasło, co powinienem zrobić?", "haslo"),
    ("Proszę, pomóż mi zmienić hasło", "haslo"),
    ("Pomocy, nie wiem co robić!", "pomoc"),
    ("Pomóż mi, mam problem", "pomoc"),
    ("Czy możesz mi pomóc?", "pomoc"),
    ("Nie wiem, jak to zrobić, potrzebuję pomocy", "pomoc"),
    ("Ratuj, nie wiem, co się dzieje", "pomoc"),
    ("Dzięki za pomoc!", "komplement"),
    ("Idealnie! Dziękuję za pomoc", "komplement"),
    ("Super, dokładnie o to mi chodziło", "komplement"),
    ("Dzięki, bardzo mi pomogłeś", "komplement"),
    ("Fajnie, że to rozwiązałeś", "komplement"),
    ("Jak dodać post na stronie?", "post"),
    ("Proszę, powiedz mi jak opublikować post", "post"),
    ("Jak mogę opublikować wpis na blogu?", "post"),
    ("Wstawienie posta na stronie - jak to zrobić?", "post"),
    ("Chciałbym dodać nowy post na moją stronę", "post"),
    ("Jakie technologie są używane w tej aplikacji?", "technologie"),
    ("Czym się różnią HTML i CSS?", "technologie"),
    ("Jakie technologie webowe są najnowsze?", "technologie"),
    ("Czy znasz metody programowania w Pythonie?", "technologie"),
    ("Czy wiesz, jakie są najpopularniejsze technologie w tworzeniu stron internetowych?", "technologie"),
    ("Czy ta strona jest bezpieczna?", "bezpieczeństwo"),
    ("Czy muszę martwić się o bezpieczeństwo tej witryny?", "bezpieczeństwo"),
    ("Jestem zaniepokojony bezpieczeństwem strony", "bezpieczeństwo"),
    ("Strona wygląda na bezpieczną, ale chciałbym to sprawdzić", "bezpieczeństwo"),
    ("Czy używasz bezpiecznych metod przesyłania danych?", "bezpieczeństwo"),
    ("Mam problem, coś nie działa", "blad"),
    ("Wyskakuje błąd, nie mogę przejść dalej", "blad"),
    ("Co mam zrobić, jeśli napotkałem błąd na stronie?", "blad"),
    ("Strona nie działa, pojawia się błąd", "blad"),
    ("Mam problem z aplikacją, coś się zawiesza", "blad"),
    ("Nie działa mi strona, pojawia się komunikat o błędzie", "blad"),
    ("Co to znaczy, że strona jest zablokowana?", "inne"),
    ("Czy mogę zmienić język na stronie?", "inne"),
    ("Chciałbym dowiedzieć się więcej o tej technologii", "inne"),
    ("Co oznacza ten termin techniczny?", "inne"),
    ("Czy mogę uzyskać pomoc w innej sprawie?", "inne"),
    ("Jaka jest prognoza pogody na jutro w Krakowie?", "pogoda"),
    ("Czy w Gdańsku będzie słonecznie?", "pogoda"),
    ("Jaka temperatura panuje teraz w Lublinie?", "pogoda"),
    ("Czy w Szczecinie będzie deszcz?", "pogoda"),
    ("Jakie będą warunki atmosferyczne w Katowicach?", "pogoda"),
    ("Kiedy będzie godzina szczytu w Warszawie?", "godzina"),
    ("Sprawdź godzinę w Londynie", "godzina"),
    ("Podaj mi godzinę w Nowym Jorku", "godzina"),
    ("Kiedy będzie dokładna godzina w Paryżu?", "godzina"),
    ("Jak sprawdzić godzinę w Australii?", "godzina"),
    ("Jak mogę zresetować moje hasło do konta?", "haslo"),
    ("Zapomniałem hasła, jak je odzyskać?", "haslo"),
    ("Jakie są kroki do zmiany mojego hasła?", "haslo"),
    ("Chciałbym zmienić moje hasło do aplikacji", "haslo"),
    ("Moje hasło jest za słabe, jak je poprawić?", "haslo"),
    ("Pomóż mi zrozumieć, jak działa ta aplikacja", "pomoc"),
    ("Potrzebuję wskazówek, jak poradzić sobie z tym problemem", "pomoc"),
    ("Czy możesz wyjaśnić, jak działa ten proces?", "pomoc"),
    ("Jak mogę uzyskać wsparcie w tej sprawie?", "pomoc"),
    ("Pomocy, nie wiem jak to zrobić!", "pomoc"),
    ("To naprawdę świetna robota, dziękuję!", "komplement"),
    ("Jestem pod wrażeniem, idealnie!", "komplement"),
    ("Dzięki, super porada!", "komplement"),
    ("Wow, to naprawdę imponujące!", "komplement"),
    ("Rewelacja, dzięki za pomoc!", "komplement"),
    ("Jak mogę dodać zdjęcie do mojego posta?", "post"),
    ("W jaki sposób mogę edytować opublikowany post?", "post"),
    ("Jak dodać link w poście na blogu?", "post"),
    ("Jak opublikować artykuł na mojej stronie?", "post"),
    ("Chciałbym usunąć mojego posta, jak to zrobić?", "post"),
    ("Jakie frameworki JavaScript są obecnie popularne?", "technologie"),
    ("Co to jest CSS Flexbox i jak go używać?", "technologie"),
    ("Jakie są zalety używania Pythona w data science?", "technologie"),
    ("Co to jest AJAX i jak działa?", "technologie"),
    ("Jakie są podstawy tworzenia aplikacji w HTML i CSS?", "technologie"),
    ("Jakie są najlepsze praktyki zabezpieczania strony internetowej?", "bezpieczeństwo"),
    ("Czy moja strona jest narażona na atak hakerski?", "bezpieczeństwo"),
    ("Co to jest SSL i dlaczego jest ważne dla bezpieczeństwa strony?", "bezpieczeństwo"),
    ("Czy powinienem używać dwuetapowej weryfikacji?", "bezpieczeństwo"),
    ("Czy moja aplikacja jest wystarczająco bezpieczna?", "bezpieczeństwo"),
    ("Strona nie ładuje się, co mam zrobić?", "blad"),
    ("Wyskakuje mi błąd 404, co to oznacza?", "blad"),
    ("Dlaczego mój komputer się zawiesza?", "blad"),
    ("Strona ciągle ładuje się bez końca, czy to błąd?", "blad"),
    ("Mój formularz nie wysyła się poprawnie, co robić?", "blad"),
    ("Chciałbym zmienić język na stronie", "inne"),
    ("Czy mogę zobaczyć poprzednie wersje tego dokumentu?", "inne"),
    ("Jak mogę skontaktować się z obsługą klienta?", "inne"),
    ("Co to jest wtyczka i jak ją zainstalować?", "inne"),
    ("Czy mogę zaktualizować mój profil?", "inne"),
    ("Jaka będzie prognoza pogody na weekend?", "pogoda"),
    ("Czy będzie padać w najbliższy piątek?", "pogoda"),
    ("Sprawdź, czy w Bydgoszczy będzie w nocy przymrozek", "pogoda"),
    ("Jaka jest przewidywana pogoda na jutro w Łodzi?", "pogoda"),
    ("Czy w Rzeszowie będzie burza?", "pogoda"),
    ("Jak sprawdzić dokładny czas w Tokyo?", "godzina"),
    ("Kiedy zaczyna się czas letni w Polsce?", "godzina"),
    ("O której godzinie jest spotkanie w Londynie?", "godzina"),
    ("Kiedy jest najlepsza pora do rozpoczęcia spotkania?", "godzina"),
    ("Jak zmienić strefę czasową na moim telefonie?", "godzina"),
    ("Potrzebuję pomocy przy ustawianiu silnego hasła", "haslo"),
    ("Jakie hasło jest bezpieczne?", "haslo"),
    ("Jak mogę odzyskać hasło do mojego e-maila?", "haslo"),
    ("Nie pamiętam mojego hasła, co robić?", "haslo"),
    ("Jakie są zasady tworzenia silnych haseł?", "haslo"),
    ("Jak mogę szybko nauczyć się tej technologii?", "pomoc"),
    ("Masz jakieś porady na temat pracy z tym narzędziem?", "pomoc"),
    ("Jak rozwiązać problem z moim urządzeniem?", "pomoc"),
    ("Pomóż mi zrozumieć, jak działa ta funkcja", "pomoc"),
    ("Czy możesz pomóc mi w nauce programowania?", "pomoc"),
    ("Dzięki za pomoc, bardzo to doceniam!", "komplement"),
    ("To była naprawdę dobra rada, dziękuję!", "komplement"),
    ("Dziękuję za wyjaśnienia, teraz wszystko rozumiem", "komplement"),
    ("Super rozwiązanie, naprawdę pomogłeś!", "komplement"),
    ("Rewelacyjna pomoc, naprawdę się cieszę!", "komplement"),
    ("Jak mogę edytować tytuł mojego posta?", "post"),
    ("Czy mogę zmienić datę publikacji mojego postu?", "post"),
    ("Jak dodać hashtag do mojego wpisu?", "post"),
    ("Jak zapisać post jako szkic?", "post"),
    ("Czy mogę dodać link do zewnętrznej strony w poście?", "post"),
    ("Jakie narzędzia do analizy danych są teraz najpopularniejsze?", "technologie"),
    ("Co to jest Machine Learning i jak się go stosuje?", "technologie"),
    ("Co to jest API i jak mogę go wykorzystać?", "technologie"),
    ("Jaka jest różnica między Pythonem a JavaScript?", "technologie"),
    ("Jakie technologie stosuje się w tworzeniu aplikacji mobilnych?", "technologie"),
    ("Jak sprawdzić, czy moja strona ma certyfikat SSL?", "bezpieczeństwo"),
    ("Czy mogę zabezpieczyć moją stronę za pomocą wtyczki?", "bezpieczeństwo"),
    ("Jak zabezpieczyć dane użytkowników w aplikacji?", "bezpieczeństwo"),
    ("Co to jest atak DDoS i jak się przed nim chronić?", "bezpieczeństwo"),
    ("Jakie są techniki ochrony przed phishingiem?", "bezpieczeństwo"),
    ("Błąd 500, co to oznacza?", "blad"),
    ("Strona jest niedostępna, co mam zrobić?", "blad"),
    ("Błąd w formularzu, jak go naprawić?", "blad"),
    ("Nie mogę zainstalować aplikacji, pojawia się błąd", "blad"),
    ("Strona nie ładuje się poprawnie, czy to błąd?", "blad"),
    ("Co oznacza ten błąd w systemie?", "inne"),
    ("Czy mogę dodać zdjęcie do mojego konta?", "inne"),
    ("Jak mogę uzyskać więcej informacji o tym produkcie?", "inne"),
    ("Czy mogę przywrócić usunięte dane?", "inne"),
    ("Gdzie mogę znaleźć więcej porad dotyczących tej aplikacji?", "inne"),
    ("Jaka jest prognoza pogody w Kielcach?", "pogoda"),
    ("Czy w Olsztynie będzie dzisiaj deszcz?", "pogoda"),
    ("Jaka temperatura jest w Toruniu teraz?", "pogoda"),
    ("Kiedy w końcu przestanie padać deszcz?", "pogoda"),
    ("Jaka będzie pogoda w Katowicach na weekend?", "pogoda"),
    ("Czy w Gdańsku będzie dziś ciepło?", "pogoda"),
    ("Jaka jest pogoda w Krakowie na dzisiaj?", "pogoda"),
    ("W Warszawie będzie dzisiaj wietrznie?", "pogoda"),
    ("Jakie będzie ciśnienie atmosferyczne w Lublinie?", "pogoda"),
    ("Czy w Białymstoku będzie padać deszcz w sobotę?", "pogoda"),
    ("Jaka godzina w Barcelonie?", "godzina"),
    ("Która jest godzina w Berlinie?", "godzina"),
    ("Podaj godzinę w Sydney", "godzina"),
    ("Jaką mamy godzinę w Londynie?", "godzina"),
    ("Czy w Nowym Jorku jest ta sama godzina, co w Polsce?", "godzina"),
    ("Jak sprawdzić godzinę na stronie?", "godzina"),
    ("Która jest godzina na całym świecie?", "godzina"),
    ("Jak zmienić strefę czasową na komputerze?", "godzina"),
    ("Jak ustawić czas letni w telefonie?", "godzina"),
    ("Jakiej godzinie w Warszawie jest spotkanie?", "godzina"),
    ("Potrzebuję pomocy w odzyskaniu hasła", "haslo"),
    ("Czy mogę ustawić inne hasło na moim koncie?", "haslo"),
    ("Jak zmienić swoje hasło na nowe?", "haslo"),
    ("Jak zresetować hasło do aplikacji?", "haslo"),
    ("Proszę, pomóż mi w ustawieniu hasła", "haslo"),
    ("Nie pamiętam hasła, co teraz?", "haslo"),
    ("Jak ustawić nowe hasło w serwisie?", "haslo"),
    ("Nie mogę znaleźć opcji zmiany hasła", "haslo"),
    ("Chcę zmienić swoje hasło, co robić?", "haslo"),
    ("Pomocy, zapomniałem hasła", "haslo"),
    ("Potrzebuję pomocy, bo nie wiem jak działa ta aplikacja", "pomoc"),
    ("Jak mam zrobić to zadanie?", "pomoc"),
    ("Pomocy, nie wiem jak to zrobić!", "pomoc"),
    ("Czy ktoś może mi pomóc rozwiązać ten problem?", "pomoc"),
    ("Jak uzyskać więcej informacji na temat tego narzędzia?", "pomoc"),
    ("Co powinienem zrobić, żeby to działało?", "pomoc"),
    ("Nie wiem jak rozwiązać ten problem, pomóż mi", "pomoc"),
    ("Potrzebuję wyjaśnienia, jak zainstalować tę aplikację", "pomoc"),
    ("Jak mogę rozwiązać ten problem na stronie?", "pomoc"),
    ("Pomóż mi zrozumieć ten błąd", "pomoc"),
    ("Dzięki za pomoc!", "komplement"),
    ("Rewelacja, to świetna rada!", "komplement"),
    ("Dziękuję, naprawdę mi pomogłeś!", "komplement"),
    ("Super pomoc, bardzo to doceniam", "komplement"),
    ("Dzięki za pomoc, to naprawdę zmieniło moje podejście", "komplement"),
    ("Dziękuję, to świetnie rozwiązane!", "komplement"),
    ("Dzięki za wyjaśnienie, teraz wszystko jasne", "komplement"),
    ("Fantastycznie, teraz już wiem, jak to zrobić", "komplement"),
    ("Idealnie, to była bardzo pomocna informacja", "komplement"),
    ("Jak opublikować nowy post?", "post"),
    ("Czy mogę dodać zdjęcie do mojego posta?", "post"),
    ("Jak edytować opublikowany post?", "post"),
    ("Jak wstawić link do posta?", "post"),
    ("Chciałbym opublikować artykuł na stronie", "post"),
    ("Czy mogę usunąć post po jego publikacji?", "post"),
    ("Jak dodać post na stronie?", "post"),
    ("Czy mogę napisać post na blogu?", "post"),
    ("Jak poprawić tytuł w moim poście?", "post"),
    ("Jaki framework do budowy aplikacji jest teraz popularny?", "technologie"),
    ("Czy powinienem używać Reacta czy Angulara?", "technologie"),
    ("Jak stworzyć aplikację internetową w Django?", "technologie"),
    ("Jakie są najlepsze technologie do budowy stron?", "technologie"),
    ("Czy warto używać Node.js do tworzenia aplikacji?", "technologie"),
    ("Jak działa JavaScript w przeglądarkach?", "technologie"),
    ("Czy Python jest dobrym językiem do tworzenia stron internetowych?", "technologie"),
    ("Jakie technologie są wykorzystywane w aplikacjach mobilnych?", "technologie"),
    ("Czy Vue.js to dobra opcja dla mojej aplikacji?", "technologie"),
    ("Jaka jest różnica między HTML a HTML5?", "technologie"),
    ("Czy ta strona jest zabezpieczona?", "bezpieczeństwo"),
    ("Czy muszę się martwić o prywatność moich danych na tej stronie?", "bezpieczeństwo"),
    ("Co zrobić, żeby strona była bezpieczna?", "bezpieczeństwo"),
    ("Jak sprawdzić, czy witryna jest bezpieczna?", "bezpieczeństwo"),
    ("Jak zainstalować certyfikat SSL na stronie?", "bezpieczeństwo"),
    ("Czy korzystanie z HTTPS jest konieczne?", "bezpieczeństwo"),
    ("Czy moja aplikacja jest bezpieczna przed atakami?", "bezpieczeństwo"),
    ("Jakie środki bezpieczeństwa powinienem podjąć na stronie?", "bezpieczeństwo"),
    ("Jakie są najlepsze praktyki zabezpieczania aplikacji?", "bezpieczeństwo"),
    ("Czy ta strona ma odpowiednie zabezpieczenia?", "bezpieczeństwo"),
    ("Strona się nie ładuje, co mam zrobić?", "blad"),
    ("Błąd 404, co to oznacza?", "blad"),
    ("Wyskakuje błąd podczas rejestracji, co robić?", "blad"),
    ("Nie mogę wejść na stronę, pojawia się błąd", "blad"),
    ("Co mam zrobić, gdy aplikacja przestaje działać?", "blad"),
    ("Wyskakuje mi błąd przy logowaniu, co robić?", "blad"),
    ("Błąd w formularzu, jak go naprawić?", "blad"),
    ("Strona nie działa, próbuję ponownie, ale nic się nie zmienia", "blad"),
    ("Aplikacja się zawiesza, co mam zrobić?", "blad"),
    ("Nie mogę zapisać zmian, wystąpił błąd", "blad"),
    ("Co oznacza ten błąd 500?", "blad"),
    ("Chciałbym zaktualizować swój profil", "inne"),
    ("Jak mogę znaleźć więcej informacji na ten temat?", "inne"),
    ("Gdzie mogę zgłosić problem?", "inne"),
    ("Czy mogę zmienić język aplikacji?", "inne"),
    ("Jak mogę dodać nowe konto?", "inne"),
    ("Czy mogę przywrócić usunięte dane?", "inne"),
    ("Jak mogę zmienić ustawienia w aplikacji?", "inne"),
    ("Chciałbym otrzymać powiadomienia", "inne"),
    ("Co muszę zrobić, żeby odzyskać moje konto?", "inne"),
    ("Jak mogę skonfigurować aplikację?", "inne"),
    ("Czy mogę usunąć konto?", "inne"),
    ("Jaka jest temperatura w Gorzowie?", "pogoda"),
    ("W jakich miastach będzie dzisiaj wiało?", "pogoda"),
    ("Jaka pogoda w Warszawie w nocy?", "pogoda"),
    ("Kiedy padał deszcz w Lublinie?", "pogoda"),
    ("Czy w Płocku będzie burza?", "pogoda"),
    ("Czy w Toruniu będzie w ciągu dnia wiatr?", "pogoda"),
    ("Co to jest pogodowy alarm?", "pogoda"),
    ("W jakiej temperaturze jest teraz w Katowicach?", "pogoda"),
    ("Czy w Krakowie będzie słońce w poniedziałek?", "pogoda"),
    ("Kiedy jest godzina szczytu na lotnisku?", "godzina"),
    ("Kiedy nastąpi zmiana czasu?", "godzina"),
    ("Czy teraz jest czas letni w Polsce?", "godzina"),
    ("Czy muszę ustawić strefę czasową w telefonie?", "godzina"),
    ("Jaka godzina jest w Toronto?", "godzina"),
    ("Która godzina w Tokio?", "godzina"),
    ("O której godzinie jest spotkanie w Nowym Jorku?", "godzina"),
    ("Czy godzina letnia w Polsce już minęła?", "godzina"),
    ("Jak zmienić godzinę na urządzeniu mobilnym?", "godzina"),
    ("Co to jest synchronizacja czasu?", "godzina"),
    ("Jaka jest prognoza na dziś w Poznaniu?", "pogoda"),
    ("W Rzeszowie będzie dziś wietrznie?", "pogoda"),
    ("Czy w Wrocławiu będzie dzisiaj ciepło?", "pogoda"),
    ("Kiedy ma zacząć padać deszcz w Bydgoszczy?", "pogoda"),
    ("Jaką temperaturę mamy teraz w Opolu?", "pogoda"),
    ("Czy w Gdańsku będzie dzisiaj burza?", "pogoda"),
    ("Jaka będzie prognoza pogody w Lublinie na wieczór?", "pogoda"),
    ("Czy w Krakowie dzisiaj popada?", "pogoda"),
    ("Czy w Białymstoku będzie deszcz w przyszłym tygodniu?", "pogoda"),
    ("Sprawdzam pogodę w Gorzowie Wielkopolskim, jak tam?", "pogoda"),
    ("Która jest godzina w Sydney?", "godzina"),
    ("Jaką mamy godzinę w Los Angeles?", "godzina"),
    ("Jaka godzina w Toronto?", "godzina"),
    ("W jakiej strefie czasowej jest Seul?", "godzina"),
    ("O której zaczyna się mecz w Nowym Jorku?", "godzina"),
    ("Kiedy jest najlepsza pora na spotkanie w Paryżu?", "godzina"),
    ("Która jest godzina w Warszawie na Twoim zegarku?", "godzina"),
    ("Czy w Buenos Aires mają tę samą godzinę co u nas?", "godzina"),
    ("Jak sprawdzić godzinę na telefonie w różnych strefach?", "godzina"),
    ("Co oznacza zmiana godziny letniej w Polsce?", "godzina"),
    ("Potrzebuję zmienić swoje hasło, jak to zrobić?", "haslo"),
    ("Jak mogę zresetować moje hasło do Facebooka?", "haslo"),
    ("Chciałbym ustawić długie hasło, co radzisz?", "haslo"),
    ("Czy jest jakiś sposób na zapamiętanie silnego hasła?", "haslo"),
    ("Jakie hasło jest bezpieczne do mojego konta?", "haslo"),
    ("Mam problem z hasłem do konta, jak je odzyskać?", "haslo"),
    ("Moje hasło jest za słabe, jak je poprawić?", "haslo"),
    ("Jak mogę zabezpieczyć swoje konto zmieniając hasło?", "haslo"),
    ("Chciałbym zmienić moje hasło do aplikacji bankowej", "haslo"),
    ("Zapomniałem hasła do e-maila, co teraz?", "haslo"),
    ("Potrzebuję pomocy przy instalacji tej aplikacji", "pomoc"),
    ("Jak mogę poprawnie skonfigurować tę aplikację?", "pomoc"),
    ("Jaki jest najlepszy sposób na rozwiązywanie problemów z komputerem?", "pomoc"),
    ("Pomóż mi znaleźć odpowiednie ustawienia w tej aplikacji", "pomoc"),
    ("Czy mógłbyś mi pomóc w naprawie tej funkcji?", "pomoc"),
    ("Jak mogę rozwiązać problem z moim urządzeniem mobilnym?", "pomoc"),
    ("Czy możesz pomóc mi w naprawie tego błędu?", "pomoc"),
    ("Jakie są zalecenia dotyczące korzystania z tej aplikacji?", "pomoc"),
    ("Potrzebuję wyjaśnienia na temat działania tej funkcji", "pomoc"),
    ("Jak mam dodać komentarz na stronie?", "post"),
    ("Czy mogę opublikować zdjęcie w moim poście?", "post"),
    ("Jak dodać tekst do posta na blogu?", "post"),
    ("Chciałbym napisać post o tym wydarzeniu, jak to zrobić?", "post"),
    ("Jak mogę edytować opublikowany artykuł?", "post"),
    ("Czy mogę napisać post na stronie internetowej?", "post"),
    ("Jak wstawić link do swojego posta?", "post"),
    ("Chciałbym usunąć swój post, jak to zrobić?", "post"),
    ("Jakie opcje mogę wybrać przy publikowaniu posta?", "post"),
    ("Co to jest framework w kontekście technologii?", "technologie"),
    ("Jakie języki programowania są obecnie najpopularniejsze?", "technologie"),
    ("Jakie narzędzia do analizy danych warto znać?", "technologie"),
    ("Jakie są najnowsze technologie w tworzeniu stron internetowych?", "technologie"),
    ("Czy Python jest lepszy od Javy w tworzeniu aplikacji?", "technologie"),
    ("Co to jest API i jak mogę z niego skorzystać?", "technologie"),
    ("Jaka jest różnica między Pythonem a C++?", "technologie"),
    ("Co to jest blockchain i jak działa?", "technologie"),
    ("Czy warto uczyć się PHP w 2025 roku?", "technologie"),
    ("Jak zainstalować certyfikat SSL na mojej stronie?", "bezpieczeństwo"),
    ("Czy strona jest bezpieczna, gdy używa HTTP?", "bezpieczeństwo"),
    ("Czy moja aplikacja jest odporna na ataki?", "bezpieczeństwo"),
    ("Jakie są zagrożenia związane z brakiem SSL na stronie?", "bezpieczeństwo"),
    ("Jak mogę poprawić bezpieczeństwo mojej witryny?", "bezpieczeństwo"),
    ("Czy muszę zmieniać hasła na stronach internetowych?", "bezpieczeństwo"),
    ("Co zrobić, żeby zabezpieczyć moje dane przed kradzieżą?", "bezpieczeństwo"),
    ("Jakie są zagrożenia związane z phishingiem?", "bezpieczeństwo"),
    ("Czy muszę używać dwuetapowej weryfikacji na moim koncie?", "bezpieczeństwo"),
    ("Jak mogę sprawdzić bezpieczeństwo mojej strony?", "bezpieczeństwo"),
    ("Co mam zrobić, gdy strona wyświetla błąd 404?", "blad"),
    ("Błąd aplikacji, jak go naprawić?", "blad"),
    ("Strona się nie ładuje, co może być przyczyną?", "blad"),
    ("Czy mogę naprawić błąd 500 na mojej stronie?", "blad"),
    ("Co mam zrobić, gdy moja strona wyświetla błąd 403?", "blad"),
    ("Strona nie działa, czy jest coś, co mogę zrobić?", "blad"),
    ("Zgłaszam błąd, co robić?", "blad"),
    ("Błąd przy rejestracji, jak go naprawić?", "blad"),
    ("Co mam zrobić, gdy wyskakuje mi komunikat o błędzie?", "blad"),
    ("Czy mogę przywrócić usunięte dane z aplikacji?", "inne"),
    ("Gdzie mogę znaleźć moje zapisane dane?", "inne"),
    ("Jak mogę edytować moje dane na stronie?", "inne"),
    ("Czy mogę zrobić kopię zapasową moich danych?", "inne"),
    ("Czy mogę przywrócić konto, jeśli je usunąłem?", "inne"),
    ("Jak mogę zmienić adres e-mail w moim profilu?", "inne"),
    ("Gdzie mogę znaleźć wszystkie moje posty?", "inne"),
    ("Jak mogę dodać kolejną funkcję do aplikacji?", "inne"),
    ("Czy mogę zaktualizować moje ustawienia prywatności?", "inne"),
    ("Jak mogę dodać kolejną osobę do mojej grupy?", "inne"),
    ("Jaka jest prognoza pogody na wiosnę?", "pogoda"),
    ("W jakich miastach będzie padać deszcz w tym tygodniu?", "pogoda"),
    ("Czy w Poznaniu będzie dziś słonecznie?", "pogoda"),
    ("Jakie są prognozy na lato?", "pogoda"),
    ("Jaką pogodę przewiduje się w Katowicach na weekend?", "pogoda"),
    ("Jaka będzie temperatura w Tychach?", "pogoda"),
    ("Czy w Toruniu będzie w przyszłym tygodniu śnieg?", "pogoda"),
    ("Czy w Warszawie będzie ciepło w sobotę?", "pogoda"),
    ("W jakiej temperaturze będzie dzisiaj w Krakowie?", "pogoda"),
    ("O której godzinie jest spotkanie w Seattle?", "godzina"),
    ("Jak sprawdzić czas w Tokio?", "godzina"),
    ("Która godzina w Helsinkach?", "godzina"),
    ("Jak zaktualizować czas na komputerze?", "godzina"),
    ("Jak sprawdzić godzinę w Australii?", "godzina"),
    ("Który czas obowiązuje w Szwajcarii?", "godzina"),
    ("Kiedy odbywa się zmiana godziny letniej w Polsce?", "godzina"),
    ("Czy czas w Polsce jest zgodny z czasem w Niemczech?", "godzina"),
    ("W jakiej strefie czasowej jest Amsterdam?", "godzina"),
    ("Jak zmienić moje hasło do Facebooka?", "haslo"),
    ("Zapomniałem hasła, jak je odzyskać?", "haslo"),
    ("Jakie są zasady tworzenia silnych haseł?", "haslo"),
    ("Czy mogę używać tego samego hasła w różnych aplikacjach?", "haslo"),
    ("Chciałbym wprowadzić silniejsze hasło", "haslo"),
    ("Potrzebuję zmienić moje hasło", "haslo"),
    ("Co zrobić, gdy zapomniałem swojego hasła?", "haslo"),
    ("Jak zmienić hasło na platformie?", "haslo"),
    ("Potrzebuję pomocy z ustawieniem aplikacji", "pomoc"),
    ("Czy mogę uzyskać wsparcie w instalacji programu?", "pomoc"),
    ("Potrzebuję pomocy przy logowaniu", "pomoc"),
    ("Jak mogę odzyskać dostęp do aplikacji?", "pomoc"),
    ("Pomocy, nie mogę znaleźć opcji", "pomoc"),
    ("Jak dodać zdjęcie do posta?", "post"),
    ("Chciałbym napisać artykuł na blogu", "post"),
    ("Czy mogę edytować opublikowany post?", "post"),
    ("Chciałbym zmienić treść mojego posta", "post"),
    ("Jak mogę dodać załącznik do posta?", "post"),
    ("Czy mogę edytować tekst w już opublikowanym poście?", "post"),
    ("Jak zmienić tytuł mojego posta?", "post"),
    ("Czy mogę opublikować link w poście?", "post"),
    ("Jakie technologie są najlepsze do tworzenia aplikacji?", "technologie"),
    ("Co to jest cloud computing?", "technologie"),
    ("Jak działa sztuczna inteligencja?", "technologie"),
    ("Czym jest machine learning?", "technologie"),
    ("Czy Java jest dobrym językiem do tworzenia aplikacji mobilnych?", "technologie"),
    ("Jakie technologie są wykorzystywane w tworzeniu aplikacji?", "technologie"),
    ("Czy Python jest dobry do programowania gier?", "technologie"),
    ("Jakie technologie wykorzystuje Facebook?", "technologie"),
    ("Czy HTML5 jest lepszy od HTML4?", "technologie"),
    ("Czy SSL jest obowiązkowy na stronie?", "bezpieczeństwo"),
    ("Czy włączenie HTTPS jest wymagane dla strony?", "bezpieczeństwo"),
    ("Czy strona jest bezpieczna, gdy używa tylko HTTP?", "bezpieczeństwo"),
    ("Jak zabezpieczyć moją stronę przed atakami?", "bezpieczeństwo"),
    ("Czy dwuetapowa weryfikacja jest obowiązkowa?", "bezpieczeństwo"),
    ("Czy moje dane są bezpieczne w aplikacji?", "bezpieczeństwo"),
    ("Jakie zabezpieczenia muszę wdrożyć na stronie?", "bezpieczeństwo"),
    ("Jak mogę zabezpieczyć moje konto na tej stronie?", "bezpieczeństwo"),
    ("Czy hasło jest wystarczającym zabezpieczeniem?", "bezpieczeństwo"),
    ("Czy jest jakiś sposób na poprawienie błędu 500?", "blad"),
    ("Co robić, gdy strona nie ładuje się poprawnie?", "blad"),
    ("Błąd w aplikacji, jak to naprawić?", "blad"),
    ("Nie mogę zalogować się na stronę, co mam zrobić?", "blad"),
    ("Zgłaszam błąd, co teraz?", "blad"),
    ("Nie działa mi aplikacja, co robić?", "blad"),
    ("Błąd przy rejestracji, co to może oznaczać?", "blad"),
    ("Błąd po zapisaniu zmian, co zrobić?", "blad"),
    ("Kiedy będzie słonecznie w Gdyni?", "pogoda"),
    ("Jaką temperaturę przewiduje się w Toruniu?", "pogoda"),
    ("Czy w Katowicach będzie deszcz w przyszłym tygodniu?", "pogoda"),
    ("Jaka pogoda czeka na nas w Łodzi?", "pogoda"),
    ("Czy na południu Polski będzie dziś burza?", "pogoda"),
    ("Jakie warunki atmosferyczne będą w Białymstoku?", "pogoda"),
    ("W jaki dzień w tym tygodniu może padać w Poznaniu?", "pogoda"),
    ("Będzie gorąco w Krakowie na weekend?", "pogoda"),
    ("Czy w Szczecinie przewidują opady deszczu?", "pogoda"),
    ("Jaka godzina w Japonii?", "godzina"),
    ("O której będzie rozpoczęcie meczu w Londynie?", "godzina"),
    ("Zegar w Nowym Jorku wskazuje ile?", "godzina"),
    ("Jaka jest godzina w Tokio?", "godzina"),
    ("Kiedy będzie najlepszy czas na spotkanie w Brisbane?", "godzina"),
    ("Czas letni w Polsce zaczyna się kiedy?", "godzina"),
    ("Na jaką godzinę wyznaczony jest koncert w Barcelonie?", "godzina"),
    ("Czy Londyn ma taką samą godzinę jak Berlin?", "godzina"),
    ("Mój zegar pokazuje inną godzinę, jak to naprawić?", "godzina"),
    ("Jak zmienić moje hasło na stronie?", "haslo"),
    ("Chciałbym zaktualizować moje hasło, co robić?", "haslo"),
    ("Jak włączyć dwuetapową weryfikację w moim koncie?", "haslo"),
    ("Zapomniałem hasła, co mam zrobić, aby odzyskać dostęp?", "haslo"),
    ("Czy mogę korzystać z tego samego hasła na różnych stronach?", "haslo"),
    ("Jaka jest minimalna długość hasła do konta bankowego?", "haslo"),
    ("Jakie są zasady tworzenia dobrego, bezpiecznego hasła?", "haslo"),
    ("Czy mogę zapisać hasło w przeglądarce?", "haslo"),
    ("Jakie hasła są najczęściej wykorzystywane w atakach hakerskich?", "haslo"),
    ("Potrzebuję porady na temat edytowania zdjęcia na stronie", "pomoc"),
    ("Jak mogę dodać plik PDF do mojej prezentacji?", "pomoc"),
    ("Jak wgrać plik do systemu?", "pomoc"),
    ("Czy mogę edytować opis mojego postu po jego opublikowaniu?", "pomoc"),
    ("Pomóż mi zorganizować wydarzenie na stronie", "pomoc"),
    ("Co zrobić, aby poprawnie opublikować artykuł?", "pomoc"),
    ("Jak mogę zmienić zdjęcie profilowe?", "pomoc"),
    ("Czy mogę przywrócić usuniętą wiadomość?", "pomoc"),
    ("Chciałbym dodać plik tekstowy do mojego posta", "post"),
    ("Jak dodać zdjęcie do artykułu na blogu?", "post"),
    ("Jak opublikować post w formie galerii zdjęć?", "post"),
    ("Czy mogę wrzucić link w komentarzu pod postem?", "post"),
    ("Jak edytować tytuł mojego posta?", "post"),
    ("Czy mogę udostępnić post na mojej stronie?", "post"),
    ("Jak zrobić, żeby post był widoczny tylko dla niektórych?", "post"),
    ("Jak zrobić zdjęcie do posta, żeby było najlepszej jakości?", "post"),
    ("Jak zrobić post w formacie PDF?", "post"),
    ("Czy wiesz, jak używać języka JavaScript w projekcie?", "technologie"),
    ("Jakie są nowoczesne frameworki do tworzenia aplikacji webowych?", "technologie"),
    ("Czy HTML5 wspiera wideo i audio?", "technologie"),
    ("Jakie technologie są wykorzystywane do tworzenia stron responsywnych?", "technologie"),
    ("Czy warto uczyć się Pythona do sztucznej inteligencji?", "technologie"),
    ("Jakie języki programowania są używane w tworzeniu aplikacji mobilnych?", "technologie"),
    ("Czy mogę nauczyć się CSS w tydzień?", "technologie"),
    ("Czym różni się HTML od XHTML?", "technologie"),
    ("Jaka jest rola JavaScriptu w rozwoju stron internetowych?", "technologie"),
    ("Moja strona nie działa po włączeniu HTTPS, co mogę zrobić?", "bezpieczeństwo"),
    ("Czy muszę zmieniać certyfikat SSL na stronie?", "bezpieczeństwo"),
    ("Jakie kroki należy podjąć, aby zabezpieczyć stronę przed atakami?", "bezpieczeństwo"),
    ("Czy ważne jest, aby mieć HTTPS na stronie?", "bezpieczeństwo"),
    ("Jak działa proces weryfikacji dwuetapowej?", "bezpieczeństwo"),
    ("Moje hasło zostało skradzione, co powinienem zrobić?", "bezpieczeństwo"),
    ("Czy istnieje narzędzie do sprawdzania bezpieczeństwa mojego serwera?", "bezpieczeństwo"),
    ("Jakie kroki podjąć, aby chronić dane osobowe na stronie?", "bezpieczeństwo"),
    ("Czy moja strona jest bezpieczna przed atakami DDoS?", "bezpieczeństwo"),
    ("Moja strona wyświetla błąd 404, co mogę zrobić?", "blad"),
    ("Wyskakuje mi błąd 403, jak to naprawić?", "blad"),
    ("Błąd aplikacji, nie wiem jak go rozwiązać", "blad"),
    ("Po aktualizacji wystąpił błąd, jak to naprawić?", "blad"),
    ("Czy błąd 500 oznacza, że coś jest nie tak z moim serwerem?", "blad"),
    ("Strona przestała działać po zmianach, co może być nie tak?", "blad"),
    ("Wyskakuje błąd przy dodawaniu pliku, co zrobić?", "blad"),
    ("Nie mogę połączyć się z bazą danych, co może być przyczyną?", "blad"),
    ("Błąd przy logowaniu, co teraz?", "blad"),
    ("Potrzebuję porady, jak dodać zdjęcie do posta w formacie PNG", "inne"),
    ("Jak udostępnić swój post na innych platformach?", "inne"),
    ("Jakie zdjęcia będą najlepsze do mojego artykułu?", "inne"),
    ("Czy mogę dodawać zdjęcia z internetu do moich postów?", "inne"),
    ("Czy mogę dodać plik do mojego posta w PDF?", "inne"),
    ("Jak mogę zmienić zdjęcie na moim profilu?", "inne"),
    ("Jak dodać link do posta, żeby działał na wszystkich urządzeniach?", "inne"),
    ("Potrzebuję porady, jak poprawić zabezpieczenia mojej strony", "inne"),
    ("Gdzie mogę znaleźć kursy na temat dbałości o bezpieczeństwo w sieci?", "inne"),
    ("Czy istnieją narzędzia do analizy bezpieczeństwa mojej witryny?", "inne"),
    ("Mam problem z zaktualizowaniem mojej strony, jak to zrobić?", "inne"),
    ("Czy w Gdańsku będzie dziś padać deszcz?", "pogoda"),
    ("Jakie warunki atmosferyczne czekają na Kraków w tym tygodniu?", "pogoda"),
    ("W jakiej temperaturze będziemy się kąpać w Warszawie?", "pogoda"),
    ("Czy prognoza pogody na weekend w Wrocławiu przewiduje burze?", "pogoda"),
    ("Jaka temperatura będzie w Zakopanem na początku tygodnia?", "pogoda"),
    ("Jakie są warunki pogodowe w Lublinie na dzisiaj?", "pogoda"),
    ("W jaki dzień w tym tygodniu przewidują opady deszczu w Poznaniu?", "pogoda"),
    ("Czy w Rzeszowie będzie dziś wietrznie?", "pogoda"),
    ("O której godzinie zaczyna się koncert w Berlinie?", "godzina"),
    ("Czy mogę dowiedzieć się, jaka godzina jest w Melbourne?", "godzina"),
    ("Jaką godzinę wskazuje zegar w Los Angeles?", "godzina"),
    ("Kiedy mam być w pracy w Monachium, według czasu lokalnego?", "godzina"),
    ("Czy we Francji obowiązuje inny czas?", "godzina"),
    ("W jakiej strefie czasowej znajduje się Toronto?", "godzina"),
    ("Jaki czas panuje na wschodnim wybrzeżu USA?", "godzina"),
    ("Jakie są godziny otwarcia sklepów w Pradze?", "godzina"),
    ("Jaka jest godzina na Alasce?", "godzina"),
    ("Jak mogę zresetować moje hasło na tej stronie?", "haslo"),
    ("Chciałbym zmienić hasło do konta, jak to zrobić?", "haslo"),
    ("Co zrobić, jeśli zapomniałem hasła do swojego konta?", "haslo"),
    ("Czy mogę ustawić hasło jednocześnie dla kilku kont?", "haslo"),
    ("Jak dodać kod weryfikacji do mojego konta?", "haslo"),
    ("Co zrobić, jeśli moje hasło zostało skradzione?", "haslo"),
    ("Jak ustawić hasło, które będzie trudne do złamania?", "haslo"),
    ("Czy mogę zmieniać hasło co miesiąc?", "haslo"),
    ("Jaka jest najlepsza metoda na zresetowanie hasła?", "haslo"),
    ("Gdzie mogę znaleźć pomoc w przypadku problemów z moim postem?", "pomoc"),
    ("Czy mogę edytować mój post po jego opublikowaniu?", "pomoc"),
    ("Jak mogę usunąć niechciany post?", "pomoc"),
    ("Jak dodać film do mojego artykułu?", "pomoc"),
    ("Czy mogę dodać plik wideo do postu?", "pomoc"),
    ("Chciałbym przenieść mój post do innej kategorii", "pomoc"),
    ("Jak mogę zwiększyć widoczność mojego postu?", "pomoc"),
    ("Jak poprawić post, żeby był bardziej atrakcyjny?", "pomoc"),
    ("Chciałbym podzielić się postem z moimi znajomymi", "post"),
    ("Jak wstawić emotikony do mojego posta?", "post"),
    ("Czy mogę dodać linki zewnętrzne do mojego artykułu?", "post"),
    ("Jak dodać tło do mojego posta?", "post"),
    ("Jak dodać załącznik do posta, aby inni mogli go pobrać?", "post"),
    ("Czy mogę zrobić post w formacie tekstowym i multimedialnym?", "post"),
    ("Jakie zdjęcie wybrać, żeby post był bardziej atrakcyjny?", "post"),
    ("Jak dostosować widoczność mojego posta?", "post"),
    ("Czy mogę opublikować post bez tytułu?", "post"),
    ("Co to jest API i do czego służy?", "technologie"),
    ("Jakie są zalety i wady JavaScript?", "technologie"),
    ("Czy warto uczyć się Node.js, jeśli znam już JavaScript?", "technologie"),
    ("Jakie technologie webowe są najczęściej używane do tworzenia stron?", "technologie"),
    ("Czy mogę używać CSS do tworzenia animacji?", "technologie"),
    ("Jakie są podstawy działania baz danych SQL?", "technologie"),
    ("Czym jest Git i do czego służy?", "technologie"),
    ("Jakie języki programowania są wykorzystywane w sztucznej inteligencji?", "technologie"),
    ("W jaki sposób mogę zaktualizować wersję PHP na mojej stronie?", "technologie"),
    ("Czy mój serwer jest bezpieczny przed atakami z sieci?", "bezpieczeństwo"),
    ("Co zrobić, żeby zapobiec atakom DDoS na mojej stronie?", "bezpieczeństwo"),
    ("Czy mogę korzystać z HTTP zamiast HTTPS?", "bezpieczeństwo"),
    ("Jakie certyfikaty SSL najlepiej kupić dla mojej strony?", "bezpieczeństwo"),
    ("Czy muszę dbać o aktualizację wtyczek, żeby moja strona była bezpieczna?", "bezpieczeństwo"),
    ("Jakie kroki podejmuję, aby zabezpieczyć dane na stronie?", "bezpieczeństwo"),
    ("Czy mogę włączyć weryfikację dwuetapową na moim koncie?", "bezpieczeństwo"),
    ("Jakie są najczęstsze luki bezpieczeństwa w aplikacjach webowych?", "bezpieczeństwo"),
    ("Moja strona wyświetla błąd 502, co powinienem zrobić?", "blad"),
    ("Nie mogę zalogować się do mojego konta, co zrobić?", "blad"),
    ("Wyskakuje mi błąd 403 Forbidden, jak to naprawić?", "blad"),
    ("Mój post zniknął, co zrobić?", "blad"),
    ("Po kliknięciu w link, strona nie ładuje się poprawnie", "blad"),
    ("Mój komputer pokazuje błąd po zainstalowaniu nowej aplikacji", "blad"),
    ("Co mogę zrobić, jeśli aplikacja nie działa na moim telefonie?", "blad"),
    ("Nie mogę dodać pliku do posta, co jest nie tak?", "blad"),
    ("Jaki jest sposób na rozwiązanie problemu z bazą danych?", "blad"),
    ("Jak zamienić zdjęcie na logo w moim poście?", "inne"),
    ("Czy mogę dodać film do posta, który będę mógł oglądać na urządzeniach mobilnych?", "inne"),
    ("Jakie metody publikacji postów najlepiej sprawdzają się na blogach?", "inne"),
    ("Gdzie mogę znaleźć najlepsze zdjęcia do postów?", "inne"),
    ("Jak mogę dodać kontaktowy formularz do mojego posta?", "inne"),
    ("Jak zarządzać postami na stronie, jeśli mam wielu użytkowników?", "inne"),
    ("Jak dodać opcję komentowania do mojego artykułu?", "inne"),
    ("Czy mogę publikować posty zewnętrzne na mojej stronie?", "inne"),
    ("Jakie narzędzia wspomagają publikowanie postów w internecie?", "inne"),
    ("Chciałbym zrobić moją stronę bardziej interaktywną, co mogę dodać?", "inne"),
    ("Hej", "przywitanie"),
    ("Cześć", "przywitanie"),
    ("Siema", "przywitanie"),
    ("Dzień dobry", "przywitanie"),
    ("Hej, jak się masz?", "przywitanie"),
    ("Cześć, jak się masz?", "przywitanie"),
    ("Jak się czujesz?", "przywitanie"),
    ("Cześć, co słychać?", "przywitanie"),
    ("Witaj", "przywitanie"),
    ("Siema, co tam?", "przywitanie"),
    ("Hej, co słychać?", "przywitanie"),
    ("Cześć, co u ciebie?", "przywitanie"),
    ("Jak tam?", "przywitanie"),
    ("Siema, jak tam u ciebie?", "przywitanie"),
    ("Hej, jak się czujesz?", "przywitanie"),
    ("Cześć, co u ciebie słychać?", "przywitanie"),
    ("Witaj, jak się czujesz?", "przywitanie"),
    ("Cześć, jak ci minął dzień?", "przywitanie"),
    ("Hej, jak życie?", "przywitanie"),
    ("Cześć, co nowego?", "przywitanie"),
    ("hej jak sie masz", "przywitanie"),
    ("Siema, jak się czujesz?", "przywitanie"),
    ("Cześć, co u ciebie?", "przywitanie"),
    ("Hej, co tam u ciebie słychać?", "przywitanie"),
    ("Witaj, jak się masz?", "przywitanie"),
    ("Cześć, jak ci minął dzień?", "przywitanie"),
    ("Siema, co u ciebie ciekawego?", "przywitanie"),
    ("Hej, jak się czujesz dzisiaj?", "przywitanie"),
    ("Witaj, co u ciebie słychać?", "przywitanie"),
    ("Cześć, jak życie?", "przywitanie"),
    ("Siema, co nowego u ciebie?", "przywitanie"),
    ("Hej, co u ciebie słychać?", "przywitanie"),
    ("Witaj, co tam słychać?", "przywitanie"),
    ("Cześć, co tam u ciebie?", "przywitanie"),
    ("Siema, jak się masz dzisiaj?", "przywitanie"),
    ("Hej, co nowego u ciebie?", "przywitanie"),
    ("Cześć, co tam u ciebie ciekawego?", "przywitanie"),
    ("Siema, jak się czujesz?", "przywitanie"),
    ("Hej, jak się czujesz dzisiaj?", "przywitanie"),
    ("Witaj, co tam u ciebie?", "przywitanie"),
    ("Cześć, jak się masz dzisiaj?", "przywitanie"),
    ("Siema, co u ciebie nowego?", "przywitanie"),
    ("Hej, co tam u ciebie?", "przywitanie"),
    ("Cześć, co słychać u ciebie?", "przywitanie"),
    ("Siema, co słychać?", "przywitanie"),
    ("Cześć, jak tam życie?", "przywitanie"),
    ("Witaj, co u ciebie?", "przywitanie"),
    ("Hej, co ciekawego u ciebie?", "przywitanie"),
    ("Siema, jak tam u ciebie?", "przywitanie"),
    ("Cześć, jak się czujesz po weekendzie?", "przywitanie"),
    ("Witaj, jak się masz?", "przywitanie"),
    ("Siema, jak tam dzisiaj?", "przywitanie"),
    ("Cześć, jak tam po pracy?", "przywitanie"),
    ("Hej, co tam nowego?", "przywitanie"),
    ("Siema, jak tam w szkole?", "przywitanie"),
    ("Witaj, co ciekawego słychać?", "przywitanie"),
    ("Cześć, co u ciebie ciekawego?", "przywitanie"),
    ("Siema, co słychać u ciebie?", "przywitanie"),
    ("Hej, jak tam po pracy?", "przywitanie"),
    ("Witaj, co tam w życiu słychać?", "przywitanie"),
    ("Siema, jak życie?", "przywitanie"),
    ("Cześć, jak się czujesz?", "przywitanie"),
    ("Hej, jak się miewasz?", "przywitanie"),
    ("Siema, co u ciebie słychać?", "przywitanie"),
    ("Cześć, co tam u ciebie nowego?", "przywitanie"),
    ("Witaj, jak tam dzisiaj?", "przywitanie"),
    ("Siema, co tam u ciebie?", "przywitanie"),
    ("Cześć, jak tam u ciebie?", "przywitanie"),
    ("Hej, co słychać u ciebie?", "przywitanie"),
    ("Cześć, co tam w pracy?", "przywitanie"),
    ("Witaj, jak ci minął dzień?", "przywitanie"),
    ("Siema, co tam w szkole?", "przywitanie"),
    ("Cześć, co u ciebie ciekawego?", "przywitanie"),
    ("Witaj, jak się czujesz dzisiaj?", "przywitanie"),
    ("Siema, jak się czujesz dzisiaj?", "przywitanie"),
    ("Hej, jak się czujesz dzisiaj?", "przywitanie"),
    ("Cześć, jak się masz po weekendzie?", "przywitanie"),
    ("Siema, jak się czujesz po pracy?", "przywitanie"),
    ("Do zobaczenia!", "pożegnanie"),
    ("Na razie!", "pożegnanie"),
    ("Trzymaj się!", "pożegnanie"),
    ("Do widzenia!", "pożegnanie"),
    ("Pa pa!", "pożegnanie"),
    ("Do później!", "pożegnanie"),
    ("Na szybko, pa!", "pożegnanie"),
    ("Trzymaj się ciepło!", "pożegnanie"),
    ("Do jutra!", "pożegnanie"),
    ("Pa, do zobaczenia!", "pożegnanie"),
    ("Baw się dobrze, na razie!", "pożegnanie"),
    ("Na razie, do zobaczenia!", "pożegnanie"),
    ("Do następnego razu!", "pożegnanie"),
    ("Pa, trzymaj się!", "pożegnanie"),
    ("Do usłyszenia!", "pożegnanie"),
    ("Na razie, trzymaj się!", "pożegnanie"),
    ("Do zobaczenia wkrótce!", "pożegnanie"),
    ("Bądź w kontakcie, pa!", "pożegnanie"),
    ("Do później, trzymaj się!", "pożegnanie"),
    ("Pa, miłego dnia!", "pożegnanie"),
    ("Pa, powodzenia!", "pożegnanie"),
    ("Do kolejnego razu!", "pożegnanie"),
    ("Do usłyszenia wkrótce!", "pożegnanie"),
    ("Pa, na razie!", "pożegnanie"),
    ("Trzymaj się, do następnego!", "pożegnanie"),
    ("Baw się dobrze, na razie!", "pożegnanie"),
    ("Pa, miłego dnia!", "pożegnanie"),
    ("Cześć, na razie!", "pożegnanie"),
    ("Do usłyszenia wkrótce!", "pożegnanie"),
    ("Do zobaczenia wkrótce!", "pożegnanie"),
    ("Na razie, bądź zdrowy!", "pożegnanie"),
    ("Do zobaczenia, na razie!", "pożegnanie"),
    ("Na razie, miłego dnia!", "pożegnanie"),
    ("Baw się dobrze, pa pa!", "pożegnanie"),
    ("Pa, do zobaczenia niedługo!", "pożegnanie"),
    ("Do usłyszenia później!", "pożegnanie"),
    ("Na razie, wszystkiego dobrego!", "pożegnanie"),
    ("Trzymaj się, pa!", "pożegnanie"),
    ("Do zobaczenia, na razie!", "pożegnanie"),
    ("Pa, bądź szczęśliwy!", "pożegnanie"),
    ("Trzymaj się, miłego dnia!", "pożegnanie"),
    ("Do później, pa pa!", "pożegnanie"),
    ("Do zobaczenia, trzymaj się!", "pożegnanie"),
    ("Na razie, powodzenia!", "pożegnanie"),
    ("Pa, niech ci się wiedzie!", "pożegnanie"),
    ("Do usłyszenia, na razie!", "pożegnanie"),
    ("Na razie, trzymaj się ciepło!", "pożegnanie"),
    ("Pa, do kolejnego spotkania!", "pożegnanie"),
    ("Do następnego razu, na razie!", "pożegnanie"),
    ("Do zobaczenia wkrótce, pa!", "pożegnanie"),
    ("Trzymaj się, na razie!", "pożegnanie"),
    ("Do usłyszenia niedługo!", "pożegnanie"),
    ("Elo, do następnego!", "pożegnanie"),
    ("Pa, widzimy się!", "pożegnanie"),
    ("Na luzie, do zobaczenia!", "pożegnanie"),
    ("Cześć, niech życie płynie!", "pożegnanie"),
    ("Yo, trzymaj się!", "pożegnanie"),
    ("Spoko, pa!", "pożegnanie"),
    ("Elo, na razie!", "pożegnanie"),
    ("Do następnego, pa!", "pożegnanie"),
    ("Siema, do zobaczenia!", "pożegnanie"),
    ("Trzymaj się, elo!", "pożegnanie"),
    ("Spadam, pa!", "pożegnanie"),
    ("Daj znać, jak coś, pa!", "pożegnanie"),
    ("Zdrówka, pa!", "pożegnanie"),
    ("Odezwij się, pa!", "pożegnanie"),
    ("Na razie, ziom!", "pożegnanie"),
    ("Cześć, lecę dalej, pa!", "pożegnanie"),
    ("Siema, czekam na kolejne spotkanie!", "pożegnanie"),
    ("Dawaj, na razie!", "pożegnanie"),
    ("Yo, do następnego!", "pożegnanie"),
    ("Spokojnie, do zobaczenia!", "pożegnanie"),
    ("Będziemy w kontakcie, pa!", "pożegnanie"),
    ("Elo, do usłyszenia!", "pożegnanie"),
    ("Dzięki, na razie!", "pożegnanie"),
    ("Piona, pa!", "pożegnanie"),
    ("Do kolejnego, ziomek!", "pożegnanie"),
    ("Cześć, nie bądź obcy!", "pożegnanie"),
    ("Na razie, nie zapomnij o mnie!", "pożegnanie"),
    ("Dzięki, trzymaj się, pa!", "pożegnanie"),
    ("Siema, pozdro!", "pożegnanie"),
    ("Pa, miłego!", "pożegnanie"),
    ("Jutro, pa!", "pożegnanie"),
    ("Do zobaczenia, na szybko!", "pożegnanie"),
    ("Zaraz, pa!", "pożegnanie"),
    ("Siema, lećmy dalej!", "pożegnanie"),
    ("Do następnego spotkania, pa!", "pożegnanie"),
    ("Na razie, rób swoje!", "pożegnanie"),
    ("Elo, wracaj do mnie!", "pożegnanie"),
    ("Na luzie, spoko, pa!", "pożegnanie"),
    ("Cześć, wbijaj na chat, pa!", "pożegnanie"),
    ("Piona, na razie!", "pożegnanie"),
    ("Do szybkiego, pa!", "pożegnanie"),
    ("Yo, miłego dnia!", "pożegnanie"),
    ("Elo, widzimy się wkrótce!", "pożegnanie"),
    ("Pa, bądź zdrowy!", "pożegnanie"),
    ("Na razie, trzymaj fason!", "pożegnanie"),
    ("Siema, nie zapomnij!", "pożegnanie"),
    ("Daj znać, co u ciebie, pa!", "pożegnanie"),
    ("Na razie, niech ci się wiedzie!", "pożegnanie"),
    ("Yo, do usłyszenia!", "pożegnanie"),
    ("To nie działa, dlaczego?", "negatywne"),
    ("Nie jestem zadowolony z tej usługi.", "negatywne"),
    ("Coś poszło nie tak.", "negatywne"),
    ("Dlaczego nie mogę się zalogować?", "negatywne"),
    ("To jest strasznie wolne.", "negatywne"),
    ("Nie działa jak powinno.", "negatywne"),
    ("Mam problem z tym produktem.", "negatywne"),
    ("Jestem rozczarowany jakością.", "negatywne"),
    ("To zupełnie nie działa tak, jak obiecywaliście.", "negatywne"),
    ("Nie mogę znaleźć żadnej opcji do naprawy.", "negatywne"),
    ("Bardzo się zawiodłem na tym produkcie.", "negatywne"),
    ("Nie mogę się połączyć z internetem.", "negatywne"),
    ("Aplikacja się zawiesza.", "negatywne"),
    ("Dlaczego nie dostaję powiadomień?", "negatywne"),
    ("To jest niesamowicie irytujące.", "negatywne"),
    ("Niezadowolony z tej usługi.", "negatywne"),
    ("Dlaczego nie działa?", "negatywne"),
    ("Ten błąd ciągle się pojawia.", "negatywne"),
    ("Nie wiem, co się dzieje, ale to nie działa.", "negatywne"),
    ("Nie da się tego używać.", "negatywne"),
    ("Coś jest nie tak z moim kontem.", "negatywne"),
    ("Zdecydowanie nie polecam tego.", "negatywne"),
    ("Otrzymałem uszkodzony produkt.", "negatywne"),
    ("Nie mogę dodać tego produktu do koszyka.", "negatywne"),
    ("Dlaczego nie mogę znaleźć tej funkcji?", "negatywne"),
    ("Czuję się oszukany.", "negatywne"),
    ("Jestem bardzo rozczarowany.", "negatywne"),
    ("Nie mogę zalogować się na swoje konto.", "negatywne"),
    ("Chciałbym uzyskać zwrot pieniędzy.", "negatywne"),
    ("Dlaczego wciąż nie mam dostępu?", "negatywne"),
    ("Zamówienie zostało opóźnione.", "negatywne"),
    ("To jest bez sensu.", "negatywne"),
    ("Nie działa jak powinno.", "negatywne"),
    ("Jestem zły, że to nie działa.", "negatywne"),
    ("Zgaduję, że to jest błąd systemowy.", "negatywne"),
    ("Po co to w ogóle wprowadzać, skoro nie działa?", "negatywne"),
    ("Nie mogę znaleźć żadnej pomocy na ten temat.", "negatywne"),
    ("Mam dość tego problemu.", "negatywne"),
    ("Ciągle mam te same problemy.", "negatywne"),
    ("Nie da się tego naprawić, prawda?", "negatywne"),
    ("To najgorsza aplikacja, jaką widziałem.", "negatywne"),
    ("Dlaczego to nie działa na moim telefonie?", "negatywne"),
    ("Nie działa to wcale na moim komputerze.", "negatywne"),
    ("To jest nieakceptowalne.", "negatywne"),
    ("Nie mogę się skontaktować z obsługą klienta.", "negatywne"),
    ("Nie chcę tego więcej używać.", "negatywne"),
    ("Po co to wprowadzać, skoro nie działa?", "negatywne"),
    ("Jestem bardzo sfrustrowany.", "negatywne"),
    ("Ta strona działa najgorzej ze wszystkich.", "negatywne"),
    ("Jestem zniechęcony brakiem pomocy.", "negatywne"),
    ("Dlaczego muszę znowu wprowadzać dane?", "negatywne"),
    ("Nie mogę znaleźć odpowiedzi na moje pytanie.", "negatywne"),
    ("Jestem bardzo zawiedziony obsługą klienta.", "negatywne"),
    ("Co się stało z moim zamówieniem?", "negatywne"),
    ("Chciałem coś naprawić, ale to tylko pogorszyło sytuację.", "negatywne"),
    ("Nie chcę już tego używać.", "negatywne"),
    ("Moje konto zostało zablokowane bez powodu.", "negatywne"),
    ("Nie działa mi strona, co się dzieje?", "negatywne"),
    ("Nie jestem w stanie zrozumieć, dlaczego to nie działa.", "negatywne"),
    ("Dostałem zły produkt.", "negatywne"),
    ("To jest najgorsze, co mogło mi się przydarzyć.", "negatywne"),
    ("Nie mam pojęcia, dlaczego nie działa.", "negatywne"),
    ("Za dużo problemów, żeby to działało.", "negatywne"),
    ("Czuję się zniechęcony do korzystania z tej usługi.", "negatywne"),
    ("To wszystko jest niepotrzebnie skomplikowane.", "negatywne"),
    ("Dlaczego aplikacja ciągle się wiesza?", "negatywne"),
    ("Znowu ten sam błąd.", "negatywne"),
    ("To jest zbyt drogie, jak na to, co oferuje.", "negatywne"),
    ("Dlaczego nie mogę znaleźć żadnej pomocy?", "negatywne"),
    ("To nie jest to, czego się spodziewałem.", "negatywne"),
    ("To wszystko jest bez sensu.", "negatywne"),
    ("Dlaczego system wciąż nie działa poprawnie?", "negatywne"),
    ("Po co robić coś, co się nie sprawdza?", "negatywne"),
    ("Nie będę polecał tej usługi nikomu.", "negatywne"),
    ("Nie wiem, dlaczego wszystko się psuje.", "negatywne"),
    ("To już jest irytujące.", "negatywne"),
    ("Zbyt wiele problemów z tym produktem.", "negatywne"),
    ("Jestem naprawdę sfrustrowany.", "negatywne"),
    ("Zamówiłem produkt, który nigdy nie przyszedł.", "negatywne"),
    ("Mam już dość czekania na odpowiedź.", "negatywne"),
    ("To jest absolutnie nieakceptowalne.", "negatywne"),
    ("Nie mogę znaleźć żadnej opcji, która by działała.", "negatywne"),
    ("Wciąż nie rozwiązałem mojego problemu.", "negatywne"),
    ("Czuję, że zostałem oszukany.", "negatywne"),
    ("Nawet nie mogę się zarejestrować.", "negatywne"),
    ("Nie działa żaden sposób, który próbuję.", "negatywne"),
    ("Nie chcę już tego używać.", "negatywne"),
    ("Aplikacja nie chce się uruchomić.", "negatywne"),
    ("Nie wiem, co mam zrobić, aby to naprawić.", "negatywne"),
    ("Ta usługa jest zupełnie nieprzydatna.", "negatywne"),
    ("To jest najgorsza decyzja, jaką podjąłem.", "negatywne"),
    ("Ciągle muszę zmieniać hasło.", "negatywne"),
    ("Nie mogę zaktualizować moich danych.", "negatywne"),
    ("Nie jestem zadowolony z tej aktualizacji.", "negatywne"),
    ("Dlaczego aplikacja ciągle się zawiesza?", "negatywne"),
    ("Nie chcę już tego używać, jest za dużo problemów.", "negatywne"),
    ("To jest po prostu zbyt frustrujące.", "negatywne"),
    ("To nie działa na moim telefonie.", "negatywne"),
    ("Mój produkt jest uszkodzony.", "negatywne"),
    ("Strona internetowa nie działa poprawnie.", "negatywne"),
    ("Nie udało się zainstalować tej aplikacji.", "negatywne"),
    ("Czuję się oszukany przez wasze usługi.", "negatywne"),
    ("Nie mogę zaktualizować tego na moim koncie.", "negatywne"),
    ("Aplikacja nigdy nie działa jak powinna.", "negatywne"),
    ("Strona wciąż ładuje się w nieskończoność.", "negatywne"),
    ("Produkt nie działa zgodnie z opisem.", "negatywne"),
    ("Nie mogę znaleźć żadnej pomocy technicznej.", "negatywne"),
    ("Nie działa to na moim urządzeniu.", "negatywne"),
    ("Usługa jest bardzo zawodna.", "negatywne"),
    ("Nie mogę znaleźć żadnej opcji naprawy.", "negatywne"),
    ("Chciałbym zrezygnować z tej usługi.", "negatywne"),
    ("To wszystko jest bez sensu.", "negatywne"),
    ("Nie mogę znaleźć tego, czego szukam.", "negatywne"),
    ("Czuję, że zmarnowałem pieniądze na ten produkt.", "negatywne"),
    ("Nie mogę uzyskać pomocy od waszej obsługi.", "negatywne"),
    ("Nawet nie wiem, gdzie zaczynać z tym problemem.", "negatywne"),
    ("Jestem bardzo zawiedziony tą usługą.", "negatywne"),
    ("Dlaczego muszę ciągle ponownie wprowadzać te same dane?", "negatywne"),
    ("To aplikacja, która nie spełnia moich oczekiwań.", "negatywne"),
    ("Mam już dość tych ciągłych problemów.", "negatywne"),
    ("Czuję się zignorowany przez waszą pomoc techniczną.", "negatywne"),
    ("Nie mogę połączyć się z waszym serwerem.", "negatywne"),
    ("Ta usługa jest naprawdę zawodna.", "negatywne"),
    ("Cały czas pojawia się błąd.", "negatywne"),
    ("Nic nie działa, jak obiecywaliście.", "negatywne"),
    ("Ten produkt jest totalnym rozczarowaniem.", "negatywne"),
    ("Nie wiem, co się dzieje, ale na pewno nie działa.", "negatywne"),
    ("Błąd wciąż się pojawia.", "negatywne"),
    ("Nie mogę zmienić ustawień na moim koncie.", "negatywne"),
    ("Ciągle mam problem z instalacją.", "negatywne"),
    ("To nie jest coś, co bym polecił innym.", "negatywne"),
    ("Ta aplikacja wcale nie działa dobrze.", "negatywne"),
    ("Jestem zmuszony do ciągłego resetowania swojego konta.", "negatywne"),
    ("Nie mogę edytować moich danych.", "negatywne"),
    ("Strona ładuje się zbyt długo.", "negatywne"),
    ("Nie działa to tak, jak powinno.", "negatywne"),
    ("Zamówiłem coś, ale nie otrzymałem żadnych informacji.", "negatywne"),
    ("Jestem naprawdę zawiedziony jakością obsługi.", "negatywne"),
    ("To wszystko jest bardzo skomplikowane.", "negatywne"),
    ("Nie wiem, jak naprawić ten problem.", "negatywne"),
    ("To jest najgorsza aplikacja, jaką miałem.", "negatywne"),
    ("Co mam teraz zrobić, skoro to nie działa?", "negatywne"),
    ("Mam dość ciągłych problemów z waszą usługą.", "negatywne"),
    ("Nie mogę zalogować się na swoje konto.", "negatywne"),
    ("Znowu nie mogę dodać produktu do koszyka.", "negatywne"),
    ("To jest totalna strata czasu.", "negatywne"),
    ("Produkt, który dostałem, jest uszkodzony.", "negatywne"),
    ("Dlaczego muszę robić to wszystko od nowa?", "negatywne"),
    ("Nie potrafię rozwiązać tego problemu.", "negatywne"),
    ("Wasza pomoc techniczna nie pomogła mi wcale.", "negatywne"),
    ("Jestem naprawdę sfrustrowany.", "negatywne"),
    ("Nie wiem, dlaczego to nie działa.", "negatywne"),
    ("Aplikacja nie działa, jak powinna.", "negatywne"),
    ("Za każdym razem pojawia się ten sam błąd.", "negatywne"),
    ("Nie mogę dodać nowego użytkownika.", "negatywne"),
    ("To jest naprawdę denerwujące.", "negatywne"),
    ("Mój produkt dotarł po terminie.", "negatywne"),
    ("Nie mogę uzyskać dostępu do moich danych.", "negatywne"),
    ("Strona nie działa na żadnym z moich urządzeń.", "negatywne"),
    ("Nie udało się rozwiązać mojego problemu.", "negatywne"),
    ("Czuję się oszukany przez waszą usługę.", "negatywne"),
    ("Produkt, który kupiłem, nie działa.", "negatywne"),
    ("Dlaczego cały czas muszę logować się na nowo?", "negatywne"),
    ("Nie potrafię zainstalować tego na moim komputerze.", "negatywne"),
    ("Cały proces jest za trudny.", "negatywne"),
    ("Zamówienie zostało opóźnione i nikt mnie nie poinformował.", "negatywne"),
    ("To jest po prostu frustrujące.", "negatywne"),
    ("Chciałbym, żeby to działało jak w reklamie.", "negatywne"),
    ("Nie mogę przejść dalej z instalacją.", "negatywne"),
    ("Aplikacja ciągle się zamyka.", "negatywne"),
    ("Jestem bardzo niezadowolony z tej usługi.", "negatywne"),
    ("Nie jestem w stanie dodać nowych funkcji.", "negatywne"),
    ("Ciągle mam te same problemy z aplikacją.", "negatywne"),
    ("Nie mogę znaleźć żadnej pomocy na ten temat.", "negatywne"),
    ("Znowu pojawił się błąd.", "negatywne"),
    ("Nie chcę już tego używać.", "negatywne"),
    ("Nie mogę edytować swojego profilu.", "negatywne"),
    ("Co się dzieje z moim zamówieniem?", "negatywne"),
    ("Nie rozumiem, dlaczego to nie działa.", "negatywne"),
    ("Nie da się tego naprawić.", "negatywne"),
    ("Produkt, który otrzymałem, jest inny niż na zdjęciu.", "negatywne"),
    ("Nie mogę skontaktować się z nikim w tej sprawie.", "negatywne"),
    ("Nie mogę uzyskać odpowiedzi na swoje pytania.", "negatywne"),
    ("Cholera, czemu to nie działa?", "negatywne"),
    ("Kurde, dlaczego znowu się popsuło?", "negatywne"),
    ("Japierdziele, to nie działa wcale!", "negatywne"),
    ("O co chodzi, dlaczego nic nie działa?", "negatywne"),
    ("Dlaczego ciągle pojawia się ten błąd?", "negatywne"),
    ("Nie rozumiem, czemu to nie działa.", "negatywne"),
    ("Znowu to samo, nie działa!", "negatywne"),
    ("Serio? Znowu mam ten sam problem?", "negatywne"),
    ("Co za chaos, czemu nie działa?", "negatywne"),
    ("Jak to możliwe, że to znowu nie działa?", "negatywne"),
    ("No nie, znowu mam ten sam problem.", "negatywne"),
    ("O nie, znowu mi to nie działa.", "negatywne"),
    ("Cholera, muszę to zrobić od nowa?", "negatywne"),
    ("Aż mi się odechciewa, jak to nie działa.", "negatywne"),
    ("Co teraz? Znowu to nie działa.", "negatywne"),
    ("Dlaczego nie mogę tego naprawić?", "negatywne"),
    ("Kiedy to w końcu zacznie działać?", "negatywne"),
    ("Ile razy mam to robić, żeby zadziałało?", "negatywne"),
    ("Mówię wam, że to nie działa!", "negatywne"),
    ("Nie mogę uwierzyć, że to znowu nie działa.", "negatywne"),
    ("To się nigdy nie uda!", "negatywne"),
    ("Nie działa, co teraz?", "negatywne"),
    ("Po co to w ogóle mam, jak nie działa?", "negatywne"),
    ("Znowu to samo, to nigdy nie działa.", "negatywne"),
    ("Dlaczego nic nie działa jak trzeba?", "negatywne"),
    ("I jak to teraz naprawić?", "negatywne"),
    ("Nie, to niemożliwe, żeby znowu to nie działało!", "negatywne"),
    ("Co za porażka, jak to znowu nie działa?", "negatywne"),
    ("Po co mam to używać, skoro nie działa?", "negatywne"),
    ("Jakim cudem to nie działa?", "negatywne"),
    ("Czy to w ogóle kiedyś będzie działać?", "negatywne"),
    ("Jestem już tym wszystkim zmęczony, to nie działa.", "negatywne"),
    ("Cholera, jak to naprawić?", "negatywne"),
    ("Wszystko psuje się na raz, co za pech!", "negatywne"),
    ("Znowu muszę to naprawiać, to jakaś tragedia.", "negatywne"),
    ("Nie mam już siły na to, czemu to nie działa?", "negatywne"),
    ("Znowu te same błędy, no nie!", "negatywne"),
    ("Kiedy to zacznie działać, serio?", "negatywne"),
    ("To po prostu nie działa, co mam zrobić?", "negatywne"),
    ("Jestem już tak sfrustrowany, czemu to nie działa?", "negatywne"),
    ("W końcu, czemu to nie działa?", "negatywne"),
    ("O co tu chodzi? Znowu nie działa!", "negatywne"),
    ("Mam już dość tego, ciągle to nie działa!", "negatywne"),
    ("Jak to możliwe, że znowu to nie działa?", "negatywne"),
    ("Po prostu nie mogę tego naprawić, to bez sensu.", "negatywne"),
    ("Czemu zawsze muszę naprawiać te same błędy?", "negatywne"),
    ("To jest po prostu niewiarygodne, że to nie działa.", "negatywne"),
    ("Nie wiem, jak to naprawić, to nie działa!", "negatywne"),
    ("Chyba nigdy to nie zacznie działać.", "negatywne"),
    ("O cholera, znowu to nie działa!", "negatywne"),
    ("To jest niemożliwe, dlaczego to nie działa?", "negatywne"),
    ("Po prostu zrezygnuję, skoro to nie działa.", "negatywne")
]

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
import joblib

texts = [item[0] for item in training_data]  # pytania
labels = [item[1] for item in training_data]  # intencje


X_train, X_test, y_train, y_test = train_test_split(texts, labels, test_size=0.2, random_state=42)


model = make_pipeline(TfidfVectorizer(), SVC(kernel='linear'))# tworzy modelu
model.fit(X_train, y_train)


accuracy = model.score(X_test, y_test)# test modelu
print(f"Model osiągnął dokładność: {accuracy*100:.2f}%")

joblib.dump(model, 'model.pkl')
print("Zapisany model.pkl")